### ISSUE TITLE
auto-create soft links to /vagrant directory

### ISSUE THREAD

**Issue by gabegaster** [gabegaster/FabTools_StartKit#2]
We did this with the 'scrapers' project in puppet; it'd be nice to make that the default to easily navigate to a project directory. 

Alternatively, could make /vagrant be the directory that default ssh to. Not sure how to do that... help us google!

**Comment by deanmalmgren** [comment]
to make `/vagrant` the default ssh directory, you can muck with the `~/.bash_profile` configuration to just `cd /vagrant`. See the website project for how it does that.

**Comment by deanmalmgren** [comment]
Actually, it looks like this issue can be closed the [setup_shell_environment](https://github.com/gabegaster/FabTools_StartKit/blob/master/fabfile/provision.py#L66-L79) provisioning task takes care of this.
